# NAME: Apple Ai
# DESC: Apple Ai 规则集
# UPDATED: 2026-05-01
# FORMAT: Surge Rule Set / 规则集格式，不包含策略组

DOMAIN,apple-relay.apple.com,extended-matching
DOMAIN,apple-relay.cloudflare.com,extended-matching
DOMAIN,apple-relay.fastly-edge.com,extended-matching
DOMAIN,gspe1-ssl.ls.apple.com,extended-matching