# NAME: HKBANK
# DESC: 香港🇭🇰银行 规则集
# UPDATED: 2026-05-01
# FORMAT: Surge Rule Set / 规则集格式，不包含策略组

# 汇丰银行香港
DOMAIN-SUFFIX,hsbc.com.hk
DOMAIN-SUFFIX,hk.hsbc.com
DOMAIN,mobile.eum-appdynamics.com
DOMAIN,accdn.lpsnmedia.net
DOMAIN,collect-ap-east-1.tealiumiq.com

# 恒生银行
DOMAIN-SUFFIX,hangseng.com

# 中国银行香港
DOMAIN-SUFFIX,bochk.com
DOMAIN-KEYWORD,bochk

# 东亚银行
DOMAIN-SUFFIX,hkbea.com

# 渣打银行香港
DOMAIN-SUFFIX,sc.com.hk
DOMAIN-SUFFIX,sc.com
DOMAIN-KEYWORD,standchartbank
DOMAIN,yvn1g4-cdn-settings.appsflyersdk.com
DOMAIN,yvn1g4-launches.appsflyersdk.com

# 花旗银行香港
DOMAIN-SUFFIX,citibank.com.hk
DOMAIN-KEYWORD,citibank

# 星展银行香港
DOMAIN-SUFFIX,dbs.com.hk

# 工银亚洲
DOMAIN-SUFFIX,icbcasia.com

# 建设银行亚洲
DOMAIN-SUFFIX,asia.ccb.com
DOMAIN-SUFFIX,online.asia.ccb.com

# 华侨银行香港 / 华侨永亨
DOMAIN-SUFFIX,ocbc.com.hk
DOMAIN-SUFFIX,ocbcwhhk.com

# 大新银行
DOMAIN-SUFFIX,dahsing.com

# 招商永隆
DOMAIN-SUFFIX,cmbwinglungbank.com

# 中信国际
DOMAIN-SUFFIX,cncbinternational.com

# 南洋银行
DOMAIN-SUFFIX,ncb.com.hk

# ZA Bank / ZA Group
DOMAIN-SUFFIX,zajourney.com
DOMAIN-SUFFIX,za.group
DOMAIN-SUFFIX,zaticdn.com
DOMAIN-SUFFIX,zafinsvc.com

# Ant Bank / 蚂蚁银行香港
DOMAIN-SUFFIX,antbank.hk
DOMAIN-SUFFIX,antbank.com.hk
DOMAIN-KEYWORD,antbank

# Airstar Bank / 天星银行
DOMAIN-SUFFIX,airstarbank.com
DOMAIN-SUFFIX,elebank.com

# livi Bank / 理慧银行
DOMAIN-SUFFIX,livi.bank

# WeLab Bank
DOMAIN-SUFFIX,welab.bank

# 富融银行
DOMAIN-SUFFIX,fusionbank.com

# Mox Bank
DOMAIN-SUFFIX,mox.com
