# -----------------------------------------------
# [银行]：新加坡银行  [Default: SG]
# -----------------------------------------------

# DBS / POSB
DOMAIN-SUFFIX,dbs.com.sg
DOMAIN-SUFFIX,dbs.com
DOMAIN-SUFFIX,posb.com.sg

# OCBC / 华侨银行 / Bank of Singapore
DOMAIN-SUFFIX,ocbc.com
DOMAIN-SUFFIX,bankofsingapore.com

# UOB / 大华银行
DOMAIN-SUFFIX,uob.com.sg
DOMAIN-SUFFIX,uobgroup.com

# HSBC Singapore / 汇丰新加坡
DOMAIN-SUFFIX,hsbc.com.sg

# Citibank Singapore / 花旗新加坡
DOMAIN-SUFFIX,citibank.com.sg

# Maybank Singapore / 马来亚银行新加坡
DOMAIN-SUFFIX,maybank2u.com.sg
DOMAIN-SUFFIX,maybank.com.sg

# RHB Singapore
DOMAIN-SUFFIX,rhbgroup.com.sg

# CIMB Singapore
DOMAIN-SUFFIX,cimb.com.sg

# Bank of China Singapore / 中国银行新加坡
DOMAIN-SUFFIX,bankofchina.com
DOMAIN-SUFFIX,boc.cn

# ICBC Singapore / 工商银行新加坡
DOMAIN-SUFFIX,icbc.com.sg

# China Construction Bank Singapore / 建设银行新加坡
DOMAIN-SUFFIX,sg.ccb.com
DOMAIN-SUFFIX,sg1.ccb.com
DOMAIN-SUFFIX,ccb.com.sg

# Bank of East Asia Singapore / 东亚银行新加坡
DOMAIN-SUFFIX,hkbea.com

# ICICI Bank Singapore
DOMAIN-SUFFIX,icicibank.com.sg

# State Bank of India Singapore
DOMAIN-SUFFIX,sg.statebank

# HL Bank Singapore / 丰隆银行新加坡
DOMAIN-SUFFIX,hlbank.com.sg
DOMAIN-SUFFIX,hlbankconnect.com.sg

# Bangkok Bank Singapore / 盘谷银行新加坡
DOMAIN-SUFFIX,bangkokbank.com

# Bank of India Singapore
DOMAIN-SUFFIX,boi.com.sg

# Indian Bank Singapore
DOMAIN-SUFFIX,indianbank.sg
DOMAIN-SUFFIX,indianbank-singapore.com

# Indian Overseas Bank Singapore
DOMAIN-SUFFIX,iobsingapore.com

# BNI Singapore / 印度尼西亚国家银行新加坡
DOMAIN-SUFFIX,ptbni.com.sg

# Trust Bank Singapore
DOMAIN-SUFFIX,trustbank.sg

# GXS Bank
DOMAIN-SUFFIX,gxs.com.sg

# MariBank
DOMAIN-SUFFIX,maribank.sg

# ANEXT Bank
DOMAIN-SUFFIX,anext.com.sg

# Green Link Digital Bank
DOMAIN-SUFFIX,glbank.com
