# -----------------------------------------------
# [银行]：英国银行  [Default: UK]
# -----------------------------------------------

# 汇丰英国 / HSBC Bank UK
DOMAIN-SUFFIX,hsbc.co.uk
DOMAIN-SUFFIX,uk.hsbc.com

# Starling Bank
DOMAIN-SUFFIX,starlingbank.com

# iFast Bank
DOMAIN-SUFFIX,ifastgb.com
DOMAIN-SUFFIX,ifastcorp.com

# NatWest / 西敏寺银行
DOMAIN-SUFFIX,natwest.com

# Virgin Money / 克莱德斯代尔银行
DOMAIN-SUFFIX,virginmoneyukplc.com

# Lloyds Bank / 劳埃德银行
DOMAIN-SUFFIX,lloydsbank.com

# Tesco Bank / 乐购个人金融
DOMAIN-SUFFIX,tescobank.com

# Atom Bank / 原子银行
DOMAIN-SUFFIX,atombank.com

# Investec / 投资银行
DOMAIN-SUFFIX,investec.com

# Gatehouse Bank / 盖特豪斯银行
DOMAIN-SUFFIX,gatehousebank.com

# Secure Trust Bank / 安信信托银行
DOMAIN-SUFFIX,securetrustbank.com

# Hampden & Co. / 汉普登银行
DOMAIN-SUFFIX,hampdenandco.com

# PCF Bank
DOMAIN-SUFFIX,pcf.bank

# Barclays Bank UK / 巴克莱银行
DOMAIN-SUFFIX,barclays.co.uk

# Nationwide / 英国全国建筑协会
DOMAIN-SUFFIX,nationwide.co.uk

# Standard Chartered / 渣打银行
DOMAIN-SUFFIX,sc.co.uk

# Santander / 桑坦德银行
DOMAIN-SUFFIX,santander.co.uk

# Co-operative Bank / 合作银行
DOMAIN-SUFFIX,co-operativebank.co.uk

# Metro Bank / 都会银行
DOMAIN-SUFFIX,metrobankonline.co.uk

# TSB Bank
DOMAIN-SUFFIX,tsb.co.uk

# Paragon Bank / 派格银行
DOMAIN-SUFFIX,paragonbank.co.uk

# Aldermore Bank / 奥德莫尔银行
DOMAIN-SUFFIX,aldermore.co.uk

# Shawbrook Bank / 肖布鲁克银行
DOMAIN-SUFFIX,shawbrook.co.uk

# Ikano Bank / 伊卡诺银行
DOMAIN-SUFFIX,ikano.co.uk

# Charter Savings Bank / 查特储蓄银行
DOMAIN-SUFFIX,chartersavingsbank.co.uk
