#!/usr/bin/env python3
"""Convert Surge-style rule sets to formats used by common proxy clients."""

from __future__ import annotations

import argparse
import ipaddress
import json
import shutil
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "rules" / "source"
GENERATED = ROOT / "rules" / "generated"
SUPPORTED_TYPES = {
    "DOMAIN",
    "DOMAIN-SUFFIX",
    "DOMAIN-KEYWORD",
    "IP-CIDR",
    "IP-CIDR6",
    "IP-ASN",
}
OPTIONS = {"no-resolve", "extended-matching"}
TEXT_TARGETS = ("surge", "loon", "shadowrocket")


@dataclass(frozen=True)
class Rule:
    kind: str
    value: str
    options: tuple[str, ...] = ()

    @property
    def canonical(self) -> str:
        parts = [self.kind, self.value, *self.options]
        return ",".join(parts)


def find_sources(root: Path = SOURCE_ROOT) -> list[Path]:
    sources: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in {".conf", ".list"}:
            continue
        sources.append(path)
    return sorted(sources, key=lambda item: item.relative_to(root).as_posix().lower())


def parse_rules(path: Path) -> list[Rule]:
    rules: list[Rule] = []
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith(("#", ";")):
            continue

        parts = [part.strip() for part in line.split(",")]
        if len(parts) < 2:
            raise ValueError(f"{path}:{line_number}: rule needs at least two fields")

        kind = parts[0].upper()
        value = parts[1]
        if kind not in SUPPORTED_TYPES:
            raise ValueError(f"{path}:{line_number}: unsupported rule type {kind!r}")
        if not value:
            raise ValueError(f"{path}:{line_number}: rule value is empty")

        # A remote rule set receives its policy from the client configuration.
        # Keep known match options and deliberately discard embedded policies.
        options = tuple(part.lower() for part in parts[2:] if part.lower() in OPTIONS)
        if kind in {"IP-CIDR", "IP-CIDR6"}:
            try:
                network = ipaddress.ip_network(value, strict=False)
            except ValueError as exc:
                raise ValueError(f"{path}:{line_number}: invalid CIDR {value!r}") from exc
            expected_version = 6 if kind == "IP-CIDR6" else 4
            if network.version != expected_version:
                raise ValueError(
                    f"{path}:{line_number}: {kind} requires IPv{expected_version}, got {value!r}"
                )

        rules.append(Rule(kind, value, options))
    return rules


def header(source: Path, root: Path) -> list[str]:
    return [
        "# Generated by scripts/convert_rules.py. Do not edit.",
        f"# Source: {source.relative_to(root).as_posix()}",
        "",
    ]


def render_text(rules: list[Rule], source: Path, root: Path, target: str) -> str:
    lines = header(source, root)
    for rule in rules:
        options: list[str] = []
        if target == "surge":
            options = list(rule.options)
        elif "no-resolve" in rule.options and rule.kind in {"IP-CIDR", "IP-CIDR6"}:
            options = ["no-resolve"]
        lines.append(",".join([rule.kind, rule.value, *options]))
    return "\n".join(lines) + "\n"


def yaml_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_mihomo(rules: list[Rule], source: Path, root: Path) -> str:
    lines = header(source, root) + ["payload:"]
    for rule in rules:
        options = ["no-resolve"] if "no-resolve" in rule.options else []
        value = ",".join([rule.kind, rule.value, *options])
        lines.append(f"  - {yaml_quote(value)}")
    return "\n".join(lines) + "\n"


QUANTUMULT_X_TYPES = {
    "DOMAIN": "host",
    "DOMAIN-SUFFIX": "host-suffix",
    "DOMAIN-KEYWORD": "host-keyword",
    "IP-CIDR": "ip-cidr",
    "IP-CIDR6": "ip6-cidr",
    "IP-ASN": "ip-asn",
}


def render_quantumult_x(rules: list[Rule], source: Path, root: Path) -> str:
    lines = header(source, root)
    for rule in rules:
        parts = [QUANTUMULT_X_TYPES[rule.kind], rule.value, "proxy"]
        if "no-resolve" in rule.options and rule.kind in {"IP-CIDR", "IP-CIDR6"}:
            parts.append("no-resolve")
        lines.append(",".join(parts))
    return "\n".join(lines) + "\n"


SING_BOX_TYPES = {
    "DOMAIN": "domain",
    "DOMAIN-SUFFIX": "domain_suffix",
    "DOMAIN-KEYWORD": "domain_keyword",
    "IP-CIDR": "ip_cidr",
    "IP-CIDR6": "ip_cidr",
}


def render_sing_box(rules: list[Rule]) -> tuple[str, list[Rule]]:
    grouped: dict[str, list[str]] = {}
    unsupported: list[Rule] = []
    for rule in rules:
        field = SING_BOX_TYPES.get(rule.kind)
        if field is None:
            unsupported.append(rule)
            continue
        value = rule.value
        if rule.kind == "DOMAIN-SUFFIX" and not value.startswith("."):
            value = f".{value}"
        grouped.setdefault(field, []).append(value)

    document = {"version": 3, "rules": [grouped] if grouped else []}
    return json.dumps(document, ensure_ascii=False, indent=2) + "\n", unsupported


def output_relative(source: Path, root: Path, suffix: str) -> Path:
    return source.relative_to(root).with_suffix(suffix)


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as output:
        output.write(content)


def build(output_root: Path, root: Path = SOURCE_ROOT) -> dict[str, object]:
    sources = find_sources(root)
    if not sources:
        raise ValueError("no .Conf or .list source files found")

    manifest_sources: list[dict[str, object]] = []
    unsupported_report: list[dict[str, str]] = []

    for source in sources:
        rules = parse_rules(source)
        relative_source = source.relative_to(root).as_posix()
        for target in TEXT_TARGETS:
            destination = output_root / target / output_relative(source, root, ".list")
            write_file(destination, render_text(rules, source, root, target))

        write_file(
            output_root / "mihomo" / output_relative(source, root, ".yaml"),
            render_mihomo(rules, source, root),
        )
        write_file(
            output_root / "quantumult-x" / output_relative(source, root, ".list"),
            render_quantumult_x(rules, source, root),
        )
        sing_box_content, unsupported = render_sing_box(rules)
        write_file(
            output_root / "sing-box" / output_relative(source, root, ".json"),
            sing_box_content,
        )
        for rule in unsupported:
            unsupported_report.append(
                {"source": relative_source, "target": "sing-box", "rule": rule.canonical}
            )

        manifest_sources.append({"source": relative_source, "rules": len(rules)})

    manifest: dict[str, object] = {
        "targets": [*TEXT_TARGETS, "mihomo", "quantumult-x", "sing-box"],
        "sources": manifest_sources,
        "unsupported_rules": len(unsupported_report),
    }
    write_file(output_root / "manifest.json", json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    write_file(
        output_root / "unsupported.json",
        json.dumps(unsupported_report, ensure_ascii=False, indent=2) + "\n",
    )
    return manifest


def trees_equal(left: Path, right: Path) -> bool:
    left_files = sorted(path.relative_to(left) for path in left.rglob("*") if path.is_file())
    right_files = sorted(path.relative_to(right) for path in right.rglob("*") if path.is_file())
    if left_files != right_files:
        return False
    return all((left / path).read_bytes() == (right / path).read_bytes() for path in left_files)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that generated files are current without modifying them",
    )
    args = parser.parse_args()

    if args.check:
        with tempfile.TemporaryDirectory(prefix="rule-convert-") as temporary:
            candidate = Path(temporary) / "generated"
            build(candidate)
            if not GENERATED.exists() or not trees_equal(GENERATED, candidate):
                print("generated files are out of date", file=sys.stderr)
                return 1
        print("generated files are up to date")
        return 0

    with tempfile.TemporaryDirectory(prefix="rule-convert-", dir=ROOT) as temporary:
        candidate = Path(temporary) / "generated"
        manifest = build(candidate)
        if GENERATED.exists():
            shutil.rmtree(GENERATED)
        shutil.copytree(candidate, GENERATED)
    print(
        f"converted {len(manifest['sources'])} source files to "
        f"{len(manifest['targets'])} target formats"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
