#!/usr/bin/env python3
"""Convert upstream sing-box source rule sets to other client formats."""

from __future__ import annotations

import ipaddress
import json
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "rules" / "upstream" / "Yuu518" / "sing-box-rules"
SOURCE_MANIFEST = ROOT / "rules" / "upstream" / "Yuu518" / "sing-box-rules.UPSTREAM.json"
OUTPUT_ROOT = ROOT / "rules" / "upstream-generated"
TARGETS = ("surge", "loon", "shadowrocket", "mihomo", "quantumult-x")
ALLOWED_FIELDS = {"domain", "domain_suffix", "domain_keyword", "domain_regex", "ip_cidr"}


@dataclass(frozen=True)
class Rule:
    kind: str
    value: str

    @property
    def canonical(self) -> str:
        return f"{self.kind},{self.value}"


def find_sources(source_root: Path = SOURCE_ROOT) -> list[Path]:
    sources: list[Path] = []
    for directory_name in ("rule_set_site", "rule_set_ip"):
        directory = source_root / directory_name
        if not directory.is_dir():
            raise ValueError(f"upstream is missing {directory_name}/")
        sources.extend(directory.rglob("*.json"))
    return sorted(sources, key=lambda item: item.relative_to(source_root).as_posix())


def string_values(value: object, source: Path, field: str) -> list[str]:
    if isinstance(value, str) and value:
        return [value]
    if isinstance(value, list) and all(isinstance(item, str) and item for item in value):
        return value
    raise ValueError(f"{source}: {field} must be a string or list of non-empty strings")


def parse_source(source: Path) -> list[Rule]:
    document = json.loads(source.read_text(encoding="utf-8"))
    if not isinstance(document, dict) or not isinstance(document.get("version"), int):
        raise ValueError(f"{source}: invalid sing-box source rule-set")
    rule_objects = document.get("rules")
    if not isinstance(rule_objects, list):
        raise ValueError(f"{source}: rules must be a list")

    parsed: list[Rule] = []
    for rule_object in rule_objects:
        if not isinstance(rule_object, dict):
            raise ValueError(f"{source}: every rule must be an object")
        unknown = set(rule_object) - ALLOWED_FIELDS
        if unknown:
            raise ValueError(f"{source}: unsupported sing-box fields: {sorted(unknown)}")

        for value in string_values(rule_object.get("domain", []), source, "domain"):
            parsed.append(Rule("DOMAIN", value))
        for value in string_values(rule_object.get("domain_suffix", []), source, "domain_suffix"):
            normalized = value[1:] if value.startswith(".") else value
            parsed.append(Rule("DOMAIN-SUFFIX", normalized))
        for value in string_values(rule_object.get("domain_keyword", []), source, "domain_keyword"):
            parsed.append(Rule("DOMAIN-KEYWORD", value))
        for value in string_values(rule_object.get("domain_regex", []), source, "domain_regex"):
            parsed.append(Rule("DOMAIN-REGEX", value))
        for value in string_values(rule_object.get("ip_cidr", []), source, "ip_cidr"):
            try:
                version = ipaddress.ip_network(value, strict=False).version
            except ValueError as exc:
                raise ValueError(f"{source}: invalid CIDR {value!r}") from exc
            parsed.append(Rule("IP-CIDR6" if version == 6 else "IP-CIDR", value))
    return parsed


def header(source: Path, source_root: Path) -> list[str]:
    return [
        "# Generated by scripts/convert_upstream_rules.py. Do not edit.",
        f"# Upstream source: {source.relative_to(source_root).as_posix()}",
        "",
    ]


def render_text(rules: list[Rule], source: Path, source_root: Path) -> str:
    return "\n".join([*header(source, source_root), *(rule.canonical for rule in rules)]) + "\n"


def yaml_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_mihomo(rules: list[Rule], source: Path, source_root: Path) -> str:
    lines = [*header(source, source_root), "payload:"]
    lines.extend(f"  - {yaml_quote(rule.canonical)}" for rule in rules)
    return "\n".join(lines) + "\n"


QUANTUMULT_X_TYPES = {
    "DOMAIN": "host",
    "DOMAIN-SUFFIX": "host-suffix",
    "DOMAIN-KEYWORD": "host-keyword",
    "IP-CIDR": "ip-cidr",
    "IP-CIDR6": "ip6-cidr",
}


def render_quantumult_x(
    rules: list[Rule], source: Path, source_root: Path
) -> tuple[str, int]:
    lines = header(source, source_root)
    unsupported = 0
    for rule in rules:
        rule_type = QUANTUMULT_X_TYPES.get(rule.kind)
        if rule_type is None:
            unsupported += 1
            continue
        lines.append(f"{rule_type},{rule.value},proxy")
    return "\n".join(lines) + "\n", unsupported


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as output:
        output.write(content)


def build(
    output_root: Path,
    source_root: Path = SOURCE_ROOT,
    source_commit: str | None = None,
) -> dict[str, object]:
    sources = find_sources(source_root)
    warnings: list[dict[str, object]] = []
    total_rules = 0

    for source in sources:
        rules = parse_source(source)
        total_rules += len(rules)
        relative = source.relative_to(source_root)
        text_relative = relative.with_suffix(".list")

        for target in ("surge", "loon", "shadowrocket"):
            write_file(output_root / target / text_relative, render_text(rules, source, source_root))
        write_file(
            output_root / "mihomo" / relative.with_suffix(".yaml"),
            render_mihomo(rules, source, source_root),
        )
        quantumult_x, unsupported = render_quantumult_x(rules, source, source_root)
        write_file(output_root / "quantumult-x" / text_relative, quantumult_x)
        if unsupported:
            warnings.append(
                {
                    "source": relative.as_posix(),
                    "target": "quantumult-x",
                    "field": "domain_regex",
                    "count": unsupported,
                }
            )

    manifest: dict[str, object] = {
        "source": "Yuu518/sing-box-rules",
        "source_commit": source_commit,
        "source_files": len(sources),
        "rules": total_rules,
        "generated_targets": list(TARGETS),
        "sing_box_source": "../upstream/Yuu518/sing-box-rules",
        "warnings": sum(int(item["count"]) for item in warnings),
    }
    write_file(output_root / "manifest.json", json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    write_file(output_root / "unsupported.json", json.dumps(warnings, ensure_ascii=False, indent=2) + "\n")
    return manifest


def main() -> int:
    try:
        source_commit = json.loads(SOURCE_MANIFEST.read_text(encoding="utf-8"))["commit"]
    except (OSError, KeyError, json.JSONDecodeError) as exc:
        raise ValueError(f"invalid upstream manifest: {SOURCE_MANIFEST}") from exc

    with tempfile.TemporaryDirectory(prefix="upstream-convert-", dir=ROOT) as temporary:
        candidate = Path(temporary) / "upstream-generated"
        manifest = build(candidate, source_commit=source_commit)
        if OUTPUT_ROOT.exists():
            shutil.rmtree(OUTPUT_ROOT)
        shutil.copytree(candidate, OUTPUT_ROOT)
    print(
        f"converted {manifest['source_files']} upstream files with {manifest['rules']} rules "
        f"to {len(manifest['generated_targets'])} client formats"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
