# NAME: WeChat
# DESC: WeChat 规则集
# UPDATED: 2026-05-01
# FORMAT: Surge Rule Set / 规则集格式，不包含策略组

DOMAIN-SUFFIX,wechat.com,DIRECT,extended-matching
DOMAIN-SUFFIX,tc.qq.com,DIRECT,extended-matching
IP-ASN,132203,DIRECT,no-resolve
IP-ASN,139341,DIRECT,no-resolve